### ISSUE TITLE
Setup for running behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by ilanzel** [jimsihk/moodle-php-nginx#228]
Hi
I am trying to run this container behind Nginx Proxy Manager, mainly for automation of SSL and https installation. 
Any advice regarding ENV variables and ports setup in docker-compose file?
Thanks

**Comment by jimsihk** [comment]
Hi, I have just added some samples for supporting SSL, you may refer to the updated readme and docker-compose-replica.yml
