### ISSUE TITLE
Update to v4.3 (403) Stable

### ISSUE THREAD

**Issue by mtompkins** [jimsihk/moodle-php-nginx#247]
Thanks for maintaining this container. 
Would love to see an update to v4.3 (403) soon.

**Comment by jimsihk** [comment]
Thanks for your interest, upgrading to 4.3+ is in the roadmap. Previously I found some problem on the Moodle function after upgrade, so it is onhold. Let me arrange some time to try again soon.

**Comment by jimsihk** [comment]
4.3.1 is out! Have fun moodling :)
