### ISSUE TITLE
No CSS when changing Moodle port #

### ISSUE THREAD

**Issue by christarroja** [jimsihk/moodle-php-nginx#38]
Hi, thank you for sharing your work.

Not sure if this is a bug, but more of a question. Why doesn't my site load the CSS when I change the Moodle port in the .yml file? For example, instead of port 80, I am trying 3000:
```
ports:
      - 3000:8080
```

and the result is like this:
![image](https://user-images.githubusercontent.com/48111294/213343778-528b6101-5dc6-4c91-88dd-d59c80c5d413.png)

Rest of the .yml file is the same. And when I revert the port # back to 80, then the Moodle site works

**Comment by jimsihk** [comment]
Hi,

Glad that you find it works for you.

What is the URL you used to access the site?

If changing to another port other than 80, you will need to access via <hostname>:3000 and set the `SITE_URL` with the port as well, e.g. http://localhost:3000

If issue persists, can you try check in the browser developer mode to see what URL is trying to access for the css?

**Comment by christarroja** [comment]
_What is the URL you used to access the site?_
http://localhost:3000

SITE_URL=http://localhost:3000

Same result. Page is loading, there's just no CSS.

To add, I noticed the 'Home' links to localhost (not 3000). Also, there are ERR_CONNECTION_REFUSED errors.

![Screen Shot 2023-01-23 at 12 27 21 PM](https://user-images.githubusercontent.com/48111294/213966066-a9aa0722-436f-4520-b3a6-3be46c1d6d2b.png)

**Comment by jimsihk** [comment]
Referring to https://github.com/erseco/alpine-moodle/issues/21, it seems no easy way to do that with just this container. Suggest to explore on some custom settings in the NGINX.
